### PR TITLE
Update to build with CUDA 11.8.

### PR DESCRIPTION
**Pull request by bdice**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Rebuilding ptxcompiler with CUDA 11.8 support. Depends on https://github.com/conda-forge/nvcc-feedstock/pull/94 to build.

cc: @cwharris @jakirkham @gmarkall

### CODE REVIEW

**Comment by bdice** [comment]
@conda-forge-admin, please rerender

**Comment by bdice** [comment]
We'll need to re-run CI after the nvcc 11.8 packages are available in the CDN. Perhaps in a couple hours.

**Comment by jakirkham** [comment]
FWIW CDN mirroring is much faster these days. So is [done ~10mins after packages are uploaded]( https://conda-forge.org/docs/maintainer/maintainer_faq.html#mfaq-anaconda-delay )

**Comment by jakirkham** [comment]
Thanks for submitting this Bradley! 🙏

**Comment by jakirkham** [comment]
@conda-forge-admin, please restart CI

**Comment by jakirkham** [comment]
A couple Travis CI jobs failed due to missing packages (likely still mirroring). Have restarted them and they are running (in spite of what the CI status may indicate)

**Comment by jakirkham** [comment]
Looks like CI now passes! 🎉

**Comment by jakirkham** [comment]
Thanks Bradley! 🙏

**Pull request merged**
